// Generated by Wrangler / OpenNext
interface CloudflareEnv {
  RAZORPAY_KEY_ID?: string;
  NEXT_PUBLIC_RAZORPAY_KEY_ID?: string;
  RAZORPAY_KEY_SECRET?: string;
  RAZORPAY_WEBHOOK_SECRET?: string;
}
